name: Deploy Worker
on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        
      # 设置Node.js版本为20  
      - name: Use Node.js 20 
        uses: actions/setup-node@v2  
        with:  
          node-version: 20 
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: 'deploy --keep-vars --no-bundle'
